"""alumni profiles, connections, lowercase enum labels

Revision ID: 2f03d6d61858
Revises: 760ccb057c6f
Create Date: 2026-09-28 02:25:53.879509

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2f03d6d61858'
down_revision: str | None = '760ccb057c6f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Phase 2 created these enum types with uppercase labels (SQLAlchemy default).
    # Rename to the lowercase .value form the ERD specifies. Existing rows follow automatically.
    op.execute("ALTER TYPE user_status RENAME VALUE 'ACTIVE' TO 'active'")
    op.execute("ALTER TYPE user_status RENAME VALUE 'SUSPENDED' TO 'suspended'")
    op.execute("ALTER TYPE user_status RENAME VALUE 'DELETED' TO 'deleted'")
    op.execute("ALTER TYPE file_visibility RENAME VALUE 'PUBLIC' TO 'public'")
    op.execute("ALTER TYPE file_visibility RENAME VALUE 'PRIVATE' TO 'private'")
    op.execute("ALTER TYPE organization_type RENAME VALUE 'SCHOOL' TO 'school'")
    op.execute("ALTER TYPE organization_type RENAME VALUE 'PARTNER' TO 'partner'")
    op.execute("ALTER TYPE organization_status RENAME VALUE 'ACTIVE' TO 'active'")
    op.execute("ALTER TYPE organization_status RENAME VALUE 'INACTIVE' TO 'inactive'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'SUPER_ADMIN' TO 'super_admin'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'ADMIN' TO 'admin'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'MODERATOR' TO 'moderator'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'SCHOOL_ADMIN' TO 'school_admin'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'PARTNER_ADMIN' TO 'partner_admin'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'EVENT_MANAGER' TO 'event_manager'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'SPORTS_MANAGER' TO 'sports_manager'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'ALUMNI' TO 'alumni'")
    op.execute("ALTER TYPE membership_status RENAME VALUE 'ACTIVE' TO 'active'")
    op.execute("ALTER TYPE membership_status RENAME VALUE 'REVOKED' TO 'revoked'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('addressee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'removed', 'blocked', name='connection_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requester_id != addressee_id', name='ck_connection_not_self'),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_connection_pair')
    )
    op.create_index(op.f('ix_connections_addressee_id'), 'connections', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_connections_requester_id'), 'connections', ['requester_id'], unique=False)
    op.create_table('alumni_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('profession', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', name='verification_status'), nullable=False),
    sa.Column('verification_method', sa.Enum('admin', 'peer', 'email_domain', name='verification_method'), nullable=True),
    sa.Column('profile_visibility', sa.Enum('public', 'members_only', 'connections_only', 'private', name='profile_visibility'), nullable=False),
    sa.Column('avatar_file_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_profiles_user_id'), 'alumni_profiles', ['user_id'], unique=True)
    op.create_table('school_email_domains',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_school_email_domains_organization_id'), 'school_email_domains', ['organization_id'], unique=False)
    op.create_table('peer_vouches',
    sa.Column('vouched_user_id', sa.UUID(), nullable=False),
    sa.Column('voucher_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['vouched_user_id'], ['alumni_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_user_id'], ['alumni_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vouched_user_id', 'voucher_user_id', name='uq_peer_vouch_pair')
    )
    op.create_index(op.f('ix_peer_vouches_vouched_user_id'), 'peer_vouches', ['vouched_user_id'], unique=False)
    op.create_index(op.f('ix_peer_vouches_voucher_user_id'), 'peer_vouches', ['voucher_user_id'], unique=False)
    op.add_column('users', sa.Column('age_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age_confirmed_at')
    op.drop_index(op.f('ix_peer_vouches_voucher_user_id'), table_name='peer_vouches')
    op.drop_index(op.f('ix_peer_vouches_vouched_user_id'), table_name='peer_vouches')
    op.drop_table('peer_vouches')
    op.drop_index(op.f('ix_school_email_domains_organization_id'), table_name='school_email_domains')
    op.drop_table('school_email_domains')
    op.drop_index(op.f('ix_alumni_profiles_user_id'), table_name='alumni_profiles')
    op.drop_table('alumni_profiles')
    op.drop_index(op.f('ix_connections_requester_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_addressee_id'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
    bind = op.get_bind()
    sa.Enum(name='connection_status').drop(bind, checkfirst=True)
    sa.Enum(name='verification_status').drop(bind, checkfirst=True)
    sa.Enum(name='verification_method').drop(bind, checkfirst=True)
    sa.Enum(name='profile_visibility').drop(bind, checkfirst=True)
    # Restore Phase 2's uppercase labels.
    op.execute("ALTER TYPE user_status RENAME VALUE 'active' TO 'ACTIVE'")
    op.execute("ALTER TYPE user_status RENAME VALUE 'suspended' TO 'SUSPENDED'")
    op.execute("ALTER TYPE user_status RENAME VALUE 'deleted' TO 'DELETED'")
    op.execute("ALTER TYPE file_visibility RENAME VALUE 'public' TO 'PUBLIC'")
    op.execute("ALTER TYPE file_visibility RENAME VALUE 'private' TO 'PRIVATE'")
    op.execute("ALTER TYPE organization_type RENAME VALUE 'school' TO 'SCHOOL'")
    op.execute("ALTER TYPE organization_type RENAME VALUE 'partner' TO 'PARTNER'")
    op.execute("ALTER TYPE organization_status RENAME VALUE 'active' TO 'ACTIVE'")
    op.execute("ALTER TYPE organization_status RENAME VALUE 'inactive' TO 'INACTIVE'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'super_admin' TO 'SUPER_ADMIN'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'admin' TO 'ADMIN'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'moderator' TO 'MODERATOR'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'school_admin' TO 'SCHOOL_ADMIN'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'partner_admin' TO 'PARTNER_ADMIN'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'event_manager' TO 'EVENT_MANAGER'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'sports_manager' TO 'SPORTS_MANAGER'")
    op.execute("ALTER TYPE membership_role RENAME VALUE 'alumni' TO 'ALUMNI'")
    op.execute("ALTER TYPE membership_status RENAME VALUE 'active' TO 'ACTIVE'")
    op.execute("ALTER TYPE membership_status RENAME VALUE 'revoked' TO 'REVOKED'")
