"""security stamp for password reset invalidation

Revision ID: 903d64c0171a
Revises: c9bd46e483a8
Create Date: 2026-09-28 23:40:49.462286

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '903d64c0171a'
down_revision: str | None = 'c9bd46e483a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_stamp', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_stamp')
    # ### end Alembic commands ###
