"""skills, interests, platform role uniqueness

Revision ID: c9bd46e483a8
Revises: 2f03d6d61858
Create Date: 2026-09-28 02:46:56.356291

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c9bd46e483a8'
down_revision: str | None = '2f03d6d61858'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alumni_interests',
    sa.Column('alumni_profile_id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_profile_id'], ['alumni_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alumni_profile_id', 'interest_id')
    )
    op.create_table('alumni_skills',
    sa.Column('alumni_profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_profile_id'], ['alumni_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alumni_profile_id', 'skill_id')
    )
    op.create_index('uq_membership_platform_role', 'memberships', ['user_id', 'role'], unique=True, postgresql_where=sa.text('organization_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_membership_platform_role', table_name='memberships', postgresql_where=sa.text('organization_id IS NULL'))
    op.drop_table('alumni_skills')
    op.drop_table('alumni_interests')
    op.drop_table('skills')
    op.drop_table('interests')
    # ### end Alembic commands ###
